image: ubuntu:20.04

before_script:
 - source hadk.env

build:
  stage: build
  script:
    - bash ./all-in-on.sh
  only:
   - web
   - tags

  artifacts:
    paths:
    - out/target/product/davinci/hybris-boot.img
